### PR TITLE
Need ChefSpec 9.1.0 for https://github.com/chefspec/chefspec/issues/954

### PR DESCRIPTION
**Pull request by mark-wagner**
### Description

Need ChefSpec 9.1.0 for https://github.com/chefspec/chefspec/issues/954

### Issues Resolved

```
 NoMethodError:
       undefined method `new_resource' for ConsulCookbook::Resource::ConsulDefinition
```

### Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [ ] CHANGELOG has been updated
- [ ] Version has been bumped in metadata
- [X] Commits have been squashed, as appropriate
- [X] Commits include descriptive messages, subjects written in the imperative

### CODE REVIEW

**Review by znep — APPROVED** [review]
Oh, nice, I think that will fix the failing tests I hit in https://github.com/socrata-cookbooks/socrata-aws-ats/pull/19 as well, didn't get time to dig into the cause...
